
image: gradle:alpine

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test
  - jar

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
 stage:
  build
 script: gradle --build-cache assemble
 cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  artifacts:
    paths:
      - ./GpsUtil/build/libs/*.jar
      - ./RewardCentral/build/libs/*.jar
      - ./TripPricer/build/libs/*.jar
      - ./TourGuideApp/build/libs/*.jar

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  services:
    - docker:dind
    dependencies:
      - build
    script:
      - docker-compose up -d
      - ./gradlew test
jar:
  stage: jar
  script:
    - chmod +x ./gradlew
    - ./gradlew bootJar assemble
  artifacts:
    paths:
      - ./build/libs/*.jar