#Specify to compose version corresponding to the current file, mainly 1, 2.x and 3.x
version: "3"
#service list
services:
    #service name
  microservice-gpsUtil:
    #Set the folder where the Dockerfile is located, which can process images that need to be built with Dockerfile
    build: ./GpsUtil/.
    #Specify the running image, you can directly pull the existing image for processing
    image: gpsutil
    container_name: gpsutil
    #restart: always
    #Expose the port of the container, the format is host port: container port - 8080:8080
    ports:
        - "9000:9000"
    networks:
      - tourguide
  microservice-rewardCentral:
    build: ./RewardCentral/.
    image: rewards
    container_name: rewardcentral
    ports:
      - "8083:8083"
    networks:
      - tourguide
  microservice-tripPricer:
    build: ./TripPricer/.
    image: trippricer
    container_name: trippricer
    ports:
      - "8082:8082"
    networks:
     - tourguide
  tourGuideApp:
    build: ./TourGuideApp/.
    image: tourguide
    container_name: tourGuideapp
    ports:
     - "8080:8080"
    networks:
     - tourguide
    depends_on:
          - microservice-gpsUtil
          - microservice-rewardCentral
          - microservice-tripPricer
    #set environment variables
    environment:
     GPS_URL: gpsutil:8081
     REWARDS-URL: rewardcentral:8082
     PRICER-URL: trippricer:8083

networks:
  tourguide:
    #external: true


